codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "25...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced settings
        branches:
          - master
          - develop
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no