name: CI Jobs
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test jacoco:report
      - name: Upload to Codecov
        env:
          CODECOV_TOKEN: 2d1eadab-cedc-4812-8906-89172b9988de
        run: bash <(curl -s https://codecov.io/bash)
